from PyQt6.QtWidgets import QTableWidget, QComboBox


class TableSelect:
    def __init__(self):
        self.create_table_select_options()

    def create_table_select_options(self):
        self.table_select_option = QTableWidget(1, 1)
        self.table_select_option.setMaximumHeight(30)
        self.table_select_option.setColumnWidth(0, 150)
        self.table_select_option.horizontalHeader().setVisible(False)
        self.table_select_option.verticalHeader().setVisible(False)
        self.create_combobox_options()

    def create_combobox_options(self):
        self.combobox_select_options = QComboBox()
        options = [
            "Select option",
            "SELECT",
            "SELECT *",
            "SELECT SUM",
            "SELECT MIN",
            "SELECT MAX",
            "SELECT COUNT",
            "SELECT DISTINCT",
            "SELECT AVG",
            "SELECT ALL",
        ]
        self.combobox_select_options.addItems(options)
        self.table_select_option.setCellWidget(0, 0, self.combobox_select_options)
        self.combobox_select_options.currentIndexChanged.connect(
            self.get_combobox_select_options
        )

    def get_combobox_select_options(self):
        current_text = self.combobox_select_options.currentText()
        if current_text != "Select option":
            self.combobox_select_options.setStyleSheet(
                "QComboBox{{ color: {} }}".format("green")
            )
            if current_text == "SELECT":
                self.table_fields.show()
                self.table_fields2.show()
                self.table_case.show()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT COUNT":
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.show()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.show()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT SUM":
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.show()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT DISTINCT":
                self.table_case.hide()
                self.table_fields.show()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT *":
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT AVG":
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.show()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT MIN" or current_text == "SELECT MAX":
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.show()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.show()
                self.table_having.hide()
                self.table_order_by.hide()
            elif current_text == "SELECT ALL":
                self.table_case.hide()
                self.table_fields.show()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.show()
                self.table_join.hide()
                self.table_where.show()
                self.table_union.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
            else:
                self.table_case.hide()
                self.table_fields.hide()
                self.table_fields2.hide()
                self.table_distinct_option.hide()
                self.table_sum.hide()
                self.table_select_sum.hide()
                self.table_avg.hide()
                self.table_count.hide()
                self.table_tables.hide()
                self.table_join.hide()
                self.table_where.hide()
                self.table_and.hide()
                self.table_and_or.hide()
                self.table_group_by.hide()
                self.table_having.hide()
                self.table_order_by.hide()
        else:
            self.table_fields.hide()
            self.table_fields2.hide()
            self.table_distinct_option.hide()
            self.table_sum.hide()
            self.table_select_sum.hide()
            self.table_avg.hide()
            self.table_count.hide()
            self.table_case.hide()
            self.table_tables.hide()
            self.table_join.hide()
            self.table_where.hide()
            self.table_and.hide()
            self.table_and_or.hide()
            self.table_group_by.hide()
            self.table_having.hide()
            self.table_union.hide()
            self.table_order_by.hide()
            self.combobox_select_options.setStyleSheet(
                "QComboBox:editable{{ color: {} }}".format("black")
            )
